---
title: Een schaduweffect toevoegen
hero_image: images/banner.png
description: Voeg een schaduweffect toe aan een HTML-element.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Een schaduweffect toevoegen

